apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-todo-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-java
  template:
    spec:
      containers:
        - image: quay.io/rh_rh/todo-java:latest
          name: todo-java
          imagePullPolicy: IfNotPresent
          env:
            - name: THEME
              value: blue-theme
